name: Linter

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: Fedora
    strategy:
      matrix:
        python: [python3.9, python3.14]
    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - run: make nox session=linter-${{ matrix.python }}
